version: '3'
services:
    {{ name|replace("-", "_") }}:
        container_name: {{ name|replace("-", "_") }}
        image: {{ image }}:${IMAGE_TAG}
        networks:
            - sidecars
        {%- if port %}
        ports:
            - {{ port }}:8080
        {%- elif ports %}
        ports:
            {%- for p in ports %}
            - {{ p }}
            {%- endfor %}
        {%- endif %}
        restart: always

networks:
    sidecars:
        external: true
