version: '2'
services:
    yopa:
        container_name: goaws
        command: -debug
        image: elifesciences/goaws:1.0.1
        volumes:
            - /home/{{ pillar.elife.deploy_user.username }}/goaws/conf:/conf
        ports:
            - 4100:4100
        restart: always
