version: '3'
services:
    {{ name|replace("-", "_") }}:
        container_name: {{ name|replace("-", "_") }}
        image: {{ image }}:${IMAGE_TAG}
        networks:
            - sidecars
        {% if port %}
        ports:
            - {{ port }}:8080
        {% endif %}
        {% if ports %}
        ports:
            {% for source, target in ports.items() %}
            - {{ source }}:{{ target }}
            {% endfor %}
        {% endif %}
        restart: always

networks:
    sidecars:
        external: true
