version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres:${IMAGE_TAG}
        ports:
            - 5432:5432
        networks:
            - databases
        env_file:
            - containers.env
        restart: always

networks:
    databases:
        external: true
