version: '2'
services:
    {{ name|replace("-", "_") }}:
        container_name: {{ name|replace("-", "_") }}
        image: {{ image }}:${IMAGE_TAG}
        networks:
            - sidecars
        {% if port %}
        ports:
            - {{ port }}:8080
        {% endif %}
        restart: always

networks:
    sidecars:
        external: true
